### ISSUE TITLE
Exception while parsing ini file

### ISSUE THREAD

**Issue by Mohammad-Haris** [apimatic/jsonmapper#28]
Exception details:
`parse_ini_file(): open_basedir restriction in effect. File(/opt/path/etc/php.ini) is not within the allowed path(s): (/home/users/username/www:/home/users/username/files:/home/users/username/tmp)`

At line 119 of JsonMapper.php.

**Comment by iamdharmesh** [comment]
Blocked by this on one WP plugin, as some hosting providers apply open_basedir restriction.  I think it is better to use `get_cfg_var` here to get the `php.ini` configuration instead of reading the php.ini file directly. what do you think @Mohammad-Haris?

Thanks

**Comment by jeffpaul** [comment]
@Mohammad-Haris @asadali214 this issue is blocking some work we're trying to help with in WooCommerce and the Square integration there.  Any chance of making an update here like @iamdharmesh mentioned above?

> I think it is better to use `get_cfg_var` here to get the `php.ini` configuration instead of reading the php.ini file directly.

**Comment by usamabintariq** [comment]
Hi @jeffpaul 

We are considering this and will circle back to you on this soon.

**Comment by asadali214** [comment]
Thanks @jeffpaul, @iamdharmesh. Your feedback meant a lot to us. Actually, we were already fetching config variables using `ini_get` instead of `get_cfg_var`.

However, upon further investigation, we found that we were missing the `open_basedir` configuration that sets the allowed paths.

This missing configuration issue will be resolved through PR: https://github.com/apimatic/jsonmapper/pull/41
